### ISSUE TITLE
[WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by Ipan1988** [binance/binance-public-data#127]
Hello,

Couple days ago, I started running your Python script to download all aggtrades for all symbols for spot market.

I left the script running overnight. This morning I got this error message and this evening when I came back from work and tried to run the script again I got it again. Is it because my IP has been banned due to the massive amount of data I've been downloading?

If yes, will the problem be fixed if I wait couple of days before I run the script again?

Traceback (most recent call last):
  File "D:\Misc\Crypto\Binance\download-aggTrade.py", line 109, in <module>
    download_monthly_aggTrades(args.type, symbols, num_symbols, args.years, args.months, args.startDate, args.endDate, args.folder, args.checksum)
  File "D:\Misc\Crypto\Binance\download-aggTrade.py", line 47, in download_monthly_aggTrades
    download_file(path, file_name, date_range, folder)
  File "D:\Misc\Crypto\Binance\utility.py", line 49, in download_file
    dl_file = urllib.request.urlopen(download_url)
  File "C:\Anaconda3\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Anaconda3\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Anaconda3\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Anaconda3\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Anaconda3\lib\urllib\request.py", line 1362, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Anaconda3\lib\urllib\request.py", line 1322, in do_open
    r = h.getresponse()
  File "C:\Anaconda3\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "C:\Anaconda3\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "C:\Anaconda3\lib\http\client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Anaconda3\lib\ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Anaconda3\lib\ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by volkan-akkus-tr** [comment]
I have faced with the same problem. After updating nugets, it disappeared. 
I advise you to update any external library, especially sourced from Binance.

**Comment by Ipan1988** [comment]
I am using Anaconda Prompt to run the script.

I left it for couple of days and tried again yesterday. It works fine now and it is almost done.
