### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by yafeng520** [binance/binance-public-data#254]
During the execution of `python3 download-aggTrade.py -t um -s 1000FLOKIUSDT -endDate 2023-07-01 -skip-monthly 1 -folder target_folder -c 1`, I encountered this error: 

```
2023-08-02 17:12:25 - Error occurred while downloading symbol: 1000FLOKIUSDT. Return code: 1. Stderr: Traceback (most recent call last):
  File "/Users/fuyafeng/anaconda3/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Users/fuyafeng/anaconda3/lib/python3.11/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/fuyafeng/anaconda3/lib/python3.11/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/fuyafeng/anaconda3/lib/python3.11/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/fuyafeng/anaconda3/lib/python3.11/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/Users/fuyafeng/anaconda3/lib/python3.11/http/client.py", line 976, in send
    self.connect()
  File "/Users/fuyafeng/anaconda3/lib/python3.11/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fuyafeng/anaconda3/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fuyafeng/anaconda3/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/Users/fuyafeng/anaconda3/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer
```
I suspect this is due to sending too many requests for non-existent dates (the data for symbol 1000FLOKIUSDT from 2020-01-01 to 2023-05-26 doesn't exist), and the server returns file not found. Why do I think this? Because if I specify a date when the file does exist, such as downloading 1000FLOKIUSDT from 2023-05-26, I won't encounter this error. Do you have any solutions for this issue? For example, automatically discovering the start date from which data for a certain symbol exists.

**Comment by 2pd** [comment]
The command works for me without any problem. If the files not found, the script is able to handle and skip it.
